# 모던 JavaScript 듀토리얼 day03

- 읽을파트: [파트 1 10.1] 'try..catch'와 에러 핸들링
- 평가: 유익, 비교연산자 규칙이 어지러웠는데 과제문제풀이와 함정피하기로 핵심을 말해주어서 정리가 잘 되었다

---

## [파트 1 10.1] 'try..catch'와 에러 핸들링

- 에러가 발생하면 스크립트는 '죽고'(즉시 중단되고), 콘솔에 에러가 출력됩니다
  그러나 `try..catch` 문법을 사용하면 스크립트가 죽는걸 방지하고, 에러를 '잡아서(catch)' 더 합당한 무언가를 할 수 있게 됩니다
- `try..catch`는 동기적으로 동작합니다
  - setTimeout처럼 '스케줄 된(scheduled)' 코드에서 발생한 예외는 `try..catch`에서 잡아낼 수 없습니다
    `setTimeout`에 넘겨진 익명함수는 엔진이 `try..catch`를 떠난 다음에서야 실행되기 때문입니다
    스케줄 된 함수 내부의 예외를 잡으려면, `try..catch`를 반드시 함수 내부에 구현해야 합니다
- 에러 객체
  - 에러가 발생하면 자바스크립트는 에러 상세내용이 담긴 객체를 생성합니다
    그 후, `catch` 블록에 이 객체를 인수로 전달합니다
  - 내장 에러 전체와 에러 객체는 두 가지 주요 프로퍼티를 가집니다
    - `name`
      - 에러 이름입니다
      - e.g. 정의되지 않은 변수 때문에 발생한 에러라면 `"ReferenceError"`가 이름이 됩니다
    - `message`
      - 에러 상세 내용을 담고 있는 문자메세지
    - `stack`
      - `stack`은 표준은 아니지만 대부분의 호스트 환경에서 지원하는 프로퍼티입니다
      - 현재 호출 스택. 에러를 유발한 중첩 호출들의 순서정보를 가진 문자열입니다
    - 에러 객체는 "name: message" 형태의 문자열로 변환됩니다
- 'throw' 연산자
  - `throw` 연산자는 에러를 생성합니다
  - 에러 객체
    - 원시형 자료를 포함한 어떤 것이든 에러 객체(error object)로 사용할 수 있습니다
    - 내장 에러와의 호환을 위해 되도록 에러 객체에 `name`과 `message` 프로퍼티를 넣어주는걸 권장합니다
    - 자바스크립트는 `Error`, `SyntaxError`, `ReferenceError`, `TypeError` 등의 표준 에러 객체 관련 생성자를 지원합니다
      - 내장 생성자를 사용해 만든 내장 에러 객체의 `name` 프로퍼티는 생성자 이름과 동일한 값을 갖습니다
      - 프로퍼티 `message`의 값은 인수에서 가져옵니다
- catch는 알고 있는 에러만 처리하고 나머지는 '다시 던져야' 합니다
  - 1. catch가 모든 에러를 받습니다
  - 2. `catch(error) {...}` 블록 안에서 에러 객체 `err`를 분석합니다
    - 에러 타입을 `instanceof` 명령어로 체크합니다
    - `err.name` 프로퍼티로 에러 클래스 이름을 알 수도 있습니다
  - 3. 에러 처리 방법을 알지 못하면 `throw err`를 합니다
- `try..catch..finally` 안의 변수는 지역변수입니다
  - `try` 블록 안에서 선언한 변수는 블록 안에서만 유효한 지역변수가 됩니다
- `finally`와 `return`
  - `finally` 절은 `try..catch` 절을 빠져나가는 _어떤_ 경우에도 실행됩니다. `return`을 사용해 명시적으로 빠져나가려는 경우도 마찬가지입니다
- 전역 catch
  - Node.js -> `process.on("uncaughtException")`
  - 브라우저환경 -> `window.onerror`
